var skills = [
    "German", 
    "English", 
    "Basic Japanese", 
    "Bitcoin", 
    "Blockchain",
    "<i class='devicon-cplusplus-plain colored'></i>C++",
    "<i class='devicon-c-plain colored'></i>C",
    "C#",
    "Objective C",
    "Java",
    "JavaScript",
    "OpenGL",
    "SQL",
    "Visual Basic",
    "Winforms",
    "Python",
    "Ruby",
    "PHP",
    "HTML5",
    "CSS3",
    ".NET",
    "Unity",
    "LIBGDX",
    "Oracle",
    "Jenkins",
    "Gulp",
    "Gradle",
    "Maven",
    "Linux",
    "Mac OSX",
    "Shell / Bash",
    "NodeJS",
    "ExpressJS",
    "Testing",
    "Mocha",
    "Chai",
    "NightmareJS",
    "Junit",
    "AngularJS",
    "Ionic",
    "Android",
    "iOS",
    "AWS",
    "SVN",
    "GIT",
    "Audition",
    "Audacity",
    "Premiere",
    "Vegas",
    "Maya",
    "Blender",
    "Photoshop",
    "UI & UX",
    "Automation",
    "SCRUM",
    "Agile",
    "Apache",
    "Team lead",
    "Tech Teaching",
    "Documentation"
];
